services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: license-server-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - license-server-network

  webserver:
    image: nginx:alpine
    container_name: license-server-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - license-server-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: license-server-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: license_server
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - license-server-network

networks:
  license-server-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

